version: "3"

services:
  backend:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - database
  frontend:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - backend
  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
